---


- name: wordpress.instalation
  hosts: vagrant
  become: yes
  #environment:
  vars: 
    WP_DOMAIN: "wordpress.test.net"
    WP_ADMIN_USERNAME: "admin"
    WP_ADMIN_PASSWORD: "@admin123"
    WP_ADMIN_EMAIL: "no@spam.org"
    WP_DB_NAME: "wordpress"
    WP_DB_USERNAME: "wordpress"
    WP_PATH: "/var/www/wordpress"
    WP_DB_PASSWORD: "OySbciJ3S8KvEYo07Jr09NXBqesIWKqzUVot53EFEOnHramzWo1wjhDJftb3NsYj"  
    MYSQL_ROOT_PASSWORD: "SBPorLmM1a3UE60Kj9yStujbMTn2sITdZwkfx3ZJBW6rEXvd8K7RY0xNX3JkgTzh"  
      
  
  tasks:
    - name: Configure /etc/hosts
      lineinfile:
        dest: /etc/hosts
        line: "127.0.0.1 {{ WP_DOMAIN }}"
      
    - name: Update Package Cache
      apt:
        update_cache: yes

    - name: Install software
      package:
        name:
          - nginx 
          - php 
          - php-fpm 
          - php-mysql 
          - php-curl 
          - php-gd
          - mysql-server 
        state: present

    - name: Make sure pymysql is present
      pip:
        name: 
          - setuptools
          - distribute 
        state: present


    - name: Make sure pymysql is present
      pip:
        name: 
          - pymysql
        state: present

    - name: Uninstall apache2
      package:
        name:
          - apache2
        state: absent

    - name: Create new wordpress data base
      mysql_db:
        name:
          - "{{  WP_DB_NAME }}"      
        state: present


    - name: Set MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password' value='{{MYSQL_ROOT_PASSWORD | quote}}' vtype='password'

    - name: Confirm MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{MYSQL_ROOT_PASSWORD | quote}}' vtype='password'

    # - name: configure nginx
    #   hosts: vagrant
    #   become: true
    #   vars:
    #     nginx_path: /etc/hosts
    #     nginx_sites: "{{ $WP_DOMAIN }}/etc/nginx/sites-available/$WP_DOMAIN"
    #   tasks:
    
    # - name: Setup nginx vhost
    #   template:
    #     src=$WP_DOMAIN www.$WP_DOMAIN;
    #     dest={{ /etc/nginx/sites-available/$WP_DOMAIN }}/$WP_DOMAIN www.$WP_DOMAIN;
    
    # - name: Setup nginx conf
    #   template:
    #     listen 80;
    #     src=$WP_DOMAIN www.$WP_DOMAIN.tpl
    #     dest={{ /etc/hosts }}/$WP_DOMAIN www.$WP_DOMAIN
    
    # - name: restart nginx
    #   service:
    #     name=nginx
    #     state=restarted
        
