name: Download and extract latest Wordpress in Ubuntu

on:
  workflow_dispatch:

#env:
  
jobs:
  wordpress-build:
    runs-on: ubuntu-latest
    continue-on-error: false
    container:
      image: nginx:latest
    steps:
      - uses: actions/checkout@v3
     
      - name: Run Wordpress Bash script
        run: |
          docker ps
          #/bin/bash ./wordpress_download.sh
          #ssh-keygen -t rsa -f ./id_rsa -q -P "
          #cat ./id_rsa.pub 
