name: Deploy latest Wordpress in Ubuntu 18.04 LTS

on:
  workflow_dispatch:

#env:
  
jobs:
  wordpress-build:
    runs-on: ubuntu-18.04
    continue-on-error: false
    steps:
      - uses: actions/checkout@v3

      - name: Run Wordpress Bash script
        run: |
          /bin/bash ./wordpress.sh


