name: Download and extract latest Wordpress in Ubuntu

on:
  workflow_dispatch:

#env:
  
jobs:
  wordpress-build:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v3

      - name: Run Wordpress Bash script
        run: |
          #/bin/bash ./wordpress_download.sh
         #ssh-keygen -t rsa -f ./id_rsa -q -P "
         #cat ./id_rsa.pub 
